Authorization
galinafrost/my-wallet pull request #1
Opened 2022-11-01 19:31 UTC by galinafrost

2022-11-07 15:59 UTC, lelchek commented on src/components/Form/Form.jsx
> +      <input type="text" name="password" />
For password inputs it is better to use type='password'

2022-11-07 15:59 UTC, lelchek commented on src/components/Form/Form.jsx
> +import { logIn } from "../../redux/auth/aut-slice";
The file name would be better corrected to auth-slice

2022-11-07 15:59 UTC, lelchek commented on src/components/UserMenu/UserMenu.jsx
> +      <button type="button" onClick={() => dispatch(logOut())}>
It is better to use non-anonymous functions for events

2022-11-07 15:59 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
> +  const isLogin = useSelector((state) => state.logIn.isLogin);
`(state) => state.logIn.isLogin` It would be nice to export selectors from a file auth-slice. In this case, if there is a need to change the store, it can be done only once, without changing every file where this selector is called

2022-11-07 15:59 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
>        <Link to="/reports-page">Reports Page</Link>
It would be great if all routes were constant everywhere

2022-11-07 15:59 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
> +  useEffect(() => {
You should add an array of dependencies as the second argument to the useEffect.

2022-11-07 15:59 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
> +      navigate("/", { replace: true });
In this implementation, only the Home page is available to authorized users. And the rest (for example, the report page) will be public pages. But we need only the login page to be public.

2022-11-09 02:26 UTC, lelchek approved these changes

2022-11-09 02:26 UTC, lelchek commented on src/components/PrivatRout/PrivatRout.jsx
> +const PrivatRout = () => {
* Private

2022-11-09 02:26 UTC, lelchek commented on src/components/PrivatRout/PrivatRout.jsx
> +  const isLogin = useSelector((state) => state.logIn.isLogin);
add to hook

2022-11-09 02:26 UTC, lelchek commented on src/App.jsx
> +import PublicRout from "./components/PublicRout";
* Public Route, Private Route

2022-11-09 02:26 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
> +      <Link to={links.reportsPage}>Reports Page</Link>
Should be replaced with constants in all places where the path is not specified using constants 
https://prnt.sc/WATFkCI7kwEK

2022-11-09 02:26 UTC, lelchek commented on src/pages/HomePage/HomePage.jsx
> +      {isLogin && <UserMenu />}
This condition is not necessary here (the page is available only to logged-in users).

2022-11-09 14:45 UTC, galinafrost commented on src/components/PrivatRout/PrivatRout.jsx
> +  const isLogin = useSelector((state) => state.logIn.isLogin);
done

2022-11-09 14:45 UTC, galinafrost commented on src/components/PrivatRout/PrivatRout.jsx
> +const PrivatRout = () => {
done

2022-11-09 14:47 UTC, galinafrost commented on src/App.jsx
> +import PublicRout from "./components/PublicRout";
done

2022-11-09 14:56 UTC, galinafrost commented on src/pages/HomePage/HomePage.jsx
> +      <Link to={links.reportsPage}>Reports Page</Link>
done

2022-11-09 14:57 UTC, galinafrost commented on src/pages/HomePage/HomePage.jsx
> +      {isLogin && <UserMenu />}
done

2022-11-09 23:00 UTC, lelchek requested changes

2022-11-09 23:00 UTC, lelchek commented on src/components/UserMenu/UserMenu.jsx
> +      <button type="button" onClick={() => dispatch(logOut())}>
not fixed yet

2022-11-09 23:03 UTC, lelchek commented on src/components/PrivatRout/PrivatRout.jsx
> +  const isLogin = useSelector((state) => state.logIn.isLogin);
name of file `PrivatRout.jsx` didn't fix

2022-11-11 16:55 UTC, galinafrost commented on src/components/UserMenu/UserMenu.jsx
> +      <button type="button" onClick={() => dispatch(logOut())}>
done

2022-11-11 16:57 UTC, galinafrost commented on src/components/PrivatRout/PrivatRout.jsx
> +  const isLogin = useSelector((state) => state.logIn.isLogin);
done

2022-11-11 17:06 UTC, merged